language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "iojs-v1.2"
  - "iojs-v1.1"
  - "iojs-v1.0"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
    - node_js: "0.9"
    - node_js: "iojs-v1.1"
    - node_js: "iojs-v1.0"
